Repository amadeusine/CS449GroupProject, pull requests merged in 2019-11, with the labels that each got.

#32 #24 exporting rust types (part 1)
  nmm/lib/index.js
  nmm/native/base/src/lib.rs
  nmm/native/src/lib.rs
Labels: back-end, neon, sprint #2

#33 #24 part 2 exporting rs types
  nmm/lib/index.js
  nmm/native/base/src/lib.rs
  nmm/native/src/lib.rs
Labels: back-end, sprint #2

#36 Sprint2 tests
  nmm/lib/tests/exports.js
  nmm/native/base/src/lib.rs
  nmm/native/src/lib.rs
  nmm/package-lock.json
  nmm/package.json
Labels: FFI, back-end, sprint #2, testing

#37 Sprint2 writeup
  .gitignore
  doc/sprint2_writeup.org
  doc/sprint2_writeup.pdf
  doc/sprint2_writeup.tex
Labels: documentation, sprint #2

#39 meeting minutes, updates to sprint2 doc stuff.
  doc/minutes.md
  doc/minutes.org
  doc/sprint2_writeup.org
Labels: documentation

#35 #25 js to rust types
  nmm/lib/index.js
  nmm/lib/tests/exports.js
  nmm/native/base/src/lib.rs
  nmm/native/base/src/util.rs
  nmm/native/src/lib.rs
Labels: back-end, sprint #2

#41 Merge Sprint #2 Game Mocks
  server/views/index.ejs
Labels: browser, express, front-end, sprint #2, sprint #3

#44 Refactor .poll and Manager API
  nmm/lib/index.js
  nmm/lib/tests/exports.js
  nmm/native/base/src/lib.rs
  nmm/native/src/lib.rs
Labels: back-end, design, sprint #3

#42 PR 1 for Game Validation Logic Feature
  nmm/lib/tests/exports.js
  nmm/native/base/src/lib.rs
  nmm/native/src/lib.rs
Labels: back-end, sprint #2, sprint #3
